### ISSUE TITLE
New option: Generate constants representing attribute names

### ISSUE THREAD

**Issue by Rapster** [mklemm/jaxb2-rich-contract-plugin#12]
Hi mklemm,

I just use your plugin to inject property change listener, one word: awesome! I'm writing a propertychangelistener, and I realized that if I decide to change the name of my property, I have to change all the listener using this property otherwise if won't match the condition: (and this transparently)

```java
    private class SoftwarePropertyChangeListener implements PropertyChangeListener {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if(evt.getPropertyName().equals("software")) {
                // Do something
            }
        }
    }
```
It would be nice to generate constant in generated class representing property name. Like this I can reference using this constant, and be notified by the compiler if something has changed. 

Another example would be when you use reflection. So, i was thinking to have something like this:

```java
public class ArticleRecord
    implements Serializable
{
    public static final String SOFTWARE = "software";

    public static final String ARTICLE = "article";

    // Getters and setters
}
```
Doing this, I can do this:
```java
    private class SoftwarePropertyChangeListener implements PropertyChangeListener {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if(evt.getPropertyName().equals(ArticleRecord.SOFTWARE)) {
                // Do something
            }
        }
    }
```
Do you see my point?

**Comment by mklemm** [comment]
Hi Rapster,
yes, I see your point, and in fact, I think something like this can be really useful.
However, as a modification to your suggestion, I'd better like to put the constants in a static inner class, and name them exactly as the properties, so you could do something like:

        if(evt.getPropertyName().equals(ArticleRecord.Properties.software)) {
            ...

This makes it easier to avoid naming conflicts with other constants that might be generated in the class.
It isn't very hard to implement this, so this is on the wish list for a near future version of this plugin, or a completely new "meta model" plugin.

**Comment by Rapster** [comment]
The static inner class is a good idea and I'd use java convention naming for static attribute, meaning upper case. I'd use the same plugin since I consider it in the same scope of the other features.

**Comment by mklemm** [comment]
Hey Rapster, try the latest version 1.5.0 of the plugin, there is a new "meta" plugin class included that can do what you want and more.
Please let me know if it works for you!

**Comment by Rapster** [comment]
That's exactly what I needed, thank you very much!
