### ISSUE TITLE
Add method: removePropertyChangeListener

### ISSUE THREAD

**Issue by Rapster** [mklemm/jaxb2-rich-contract-plugin#13]
Hi,

I'm using the BoundPopertiesPlugin, I see you provide addPropertyChangeListener method during generation, I need to remove a listener but I can't 'cause it's not there. Could you please add method 'removePropertyChangeListener' method?

**Comment by mklemm** [comment]
Hi Rapster, please try the just-released version 1.4.1 of the plugin, this will generate a "removePropertyChangeListener" method.

**Comment by mklemm** [comment]
I've just released version 1.5.1. Check it out on the project page.
