### ISSUE TITLE
Extend fluent API builder to be a domain specific language

### ISSUE THREAD

**Issue by dirkhillbrecht** [mklemm/jaxb2-rich-contract-plugin#23]
Hi!

Do you know

http://blog.jooq.org/2012/01/05/the-java-fluent-api-designer-crash-course/

? It's about desinging a builder in a way that it *enforces* the programmer using it to do the "Right Thing". It does so by cleverly designed subclasses which have only those "with..." methods which are sensible
in that specific state. I wonder whether this could be applied on an XSD schema. If so, it would be a wonderful extension - XSD is all about document correctness and applying it to the JAXB builders would mean to move a whole class of errors from runtime to compile time as it would not be possible any more to create JAXB instances which do not comply the schema rules.

What do you think? Would this be a sensible extension?

Best regards,
Dirk

**Comment by mklemm** [comment]
I didn't know that article, but essentially this is what the fluent-builder-plugin is aiming at already. It currently supports the `.withXXX().withSubXXX().end()` syntax, and I also already planned to add the conditional syntax at some point. However, as I'm currently busy doing other things, that hasn't been a priority.
I someone else can do it, very good...

**Comment by dirkhillbrecht** [comment]
Hi, thanks for these first thoughts. I thought myself about this thing and found some potential problems, e.g. a <sequence> which might by much easier filled with data if insertion order is different from element order. I have no plans to start anything on this soon... Best regards, Dirk

**Comment by mklemm** [comment]
OK, so I think this can be closed
