### ISSUE TITLE
Generated code is invalid if the XML definition contains Java key words

### ISSUE THREAD

**Issue by dadrus** [mklemm/jaxb2-rich-contract-plugin#26]
Hi Mirko,

Unfortunately I have to cope with XML definitions, which I unable to influence. In my specific case those who have written the XML schema have used Java key words as attribute names. Here is an example:

```.xml
<xsd:complexType name="SomeComplexType">
	<xsd:sequence>
		<xsd:element name="scheduleTime" type="xsd:dateTime" minOccurs="0" maxOccurs="1"/>
		<xsd:element name="notify" type="TaskNotifyDeliveryMethodEnum" minOccurs="0" maxOccurs="1"/>
	</xsd:sequence>
</xsd:complexType>
```

Using the `fluent-builder` plugin results in the following code:

```.java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionID",
    "scheduleTime",
    "notify"
})
@XmlRootElement(name = "startDataMigration")
public class SomeComplexType {
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduleTime;
    protected TaskNotifyDeliveryMethodEnum notify;

    // other generated parts removed for brevity

    public com.kscs.util.jaxb.Selector<TRoot, SomeComplexType.Selector<TRoot, TParent>> notify() {
        return ((this.notify == null)?this.notify = new com.kscs.util.jaxb.Selector<TRoot, SomeComplexType.Selector<TRoot, TParent>>(this._root, this, "notify"):this.notify);
    }
}
```

The problem is the generated `notify` method which clashes with the Java `Object.notify`. There is a work around for it in using JAXB bindings. This however is annoying if one has a lot of different clashes in a lot of different modules.
Would it be possible for you to check for such issues during code generation and e.g. append/prepend a `_` to the generated Java code fragment?

Thank you.

Regards,
Dimitrij

**Comment by mklemm** [comment]
Hi Dimitrij,
this is a general issue with XJC code generation, and to my knowledge the only way around is to use JAXB binding customizations. With these, you can alter the name of any property (using the jaxb:property annotation).

**Comment by dadrus** [comment]
It was worth a try:)
I will stick with JAXB bindings then.

**Comment by mklemm** [comment]
The jaxb2-rich-contract plugins should work well together with property names that have been customized through standard JAXB binding customizations.. If not, this is a different issue...
