### ISSUE TITLE
Java8 Optional

### ISSUE THREAD

**Issue by gustavoramos00** [mklemm/jaxb2-rich-contract-plugin#29]
Hi,

Are there some plugin providing properties with the new Java8 Optional<T> class? It could be used on elements that are not required, to avoid null validations.

**Comment by mklemm** [comment]
Currently, I'm not aware of a plugin like this, and I also cannot imagine how it will be useful. Even if Optional is used, there has to be validation as soon as you really have to use its value. The only use case I can think of is to make a distinction between between elements or attributes in an XML structure that are declared "nillable=true", and those which have "minOccurs=0" or "use=optional" instead.
The "Optional" class technically is a very special case in Java 8 and shouldn't be used as a general-purpose type. For performance reasons, it is treated by the compiler internally as a pass-by-value type (a thing Java doesn't officially have), and thus has a number of limitations with regard to its usage. It is only intended as an optional return value for a method and shouldn't be used for anything else.

**Comment by gustavoramos00** [comment]
Thanks for your reply, @mklemm! I think Optional would very useful. Suppose the following XSD:

```xml
<complexType name="ct_beneficiarioDados">
	<sequence>
		<element name="numeroCarteira" type="ans:st_texto20"/>
		<element name="numeroCNS" type="ans:st_texto15" minOccurs="0"/>
	</sequence>
</complexType>
```

I would like this hypothetic Java code to be generated:

```java
public class BeneficiarioDados {

	private String numeroCarteira;
	private String numeroCNS;
	
	public String getNumeroCarteira(){
		return numeroCarteira;
	}
	
	public Optional<String> getNumeroCNS(){
		return Optional.ofNullable(numeroCNS);
	}
}
```

Since I know Optional is being used comprehensively in my project, I don´t need to check if numeroCarteira is null, because it isn't Optional... But I always have to check numeroCNS, and also I could do things like this:

```java
String data = String.format("Info: Carteira %s, CNS %s", 
	b.getNumeroCarteira(), 
	b.getNumeroCNS().orElse("Not exists"));
```

Could you give me some roadmap or insight about how to implement a plugin like that?

**Comment by mklemm** [comment]
Plugin development for JAXB is discussed on the [JAXB Website](https://jaxb.java.net/plugin.html)
This guide is intended for the JAXB reference implementation. I think it will be a good starting point.
