### ISSUE TITLE
Add support for maven-jaxb2-plugin:0.14.0

### ISSUE THREAD

**Issue by sinedsem** [mklemm/jaxb2-rich-contract-plugin#35]
ATM the latest version 1.18.0 fails with the error:

> Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (default) on project marshall: Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate: java.lang.NoSuchMethodError: com.sun.codemodel.fmt.JStaticJavaFile.<init>(Lcom/sun/codemodel/JPackage;Ljava/lang/String;Ljava/net/URL;Lcom/sun/codemodel/fmt/JStaticJavaFile$LineFilter;)V

**Comment by mklemm** [comment]
The current version of the plugin was built against JAXB 2.2. The next version will support JAXB 2.3 only, so the issue will be resolved.

**Comment by mklemm** [comment]
Resolved in 2.0.0

**Comment by Vishal-0319** [comment]
Getting an error while migrating to jdk17 

[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate (xjc) on project checkout-service-api: Execution xjc of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate failed: An API incompatibility was encountered while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0:generate: java.lang.ExceptionInInitializerError: null

Can anyone please help here
