### ISSUE TITLE
Multiple Maven executions

### ISSUE THREAD

**Issue by pbillen** [mklemm/jaxb2-rich-contract-plugin#36]
Hi,

I am getting issues when defining multiple executions. I have multiple sets of XSD/XJB files, which must be generated into a separate package. For this reason, I am using multiple Maven executions as following:

            <plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb2-plugin</artifactId>
                <version>0.14.0</version>
                <configuration>
                    <plugins>
                        <plugin>
                            <groupId>net.codesup.util</groupId>
                            <artifactId>jaxb2-rich-contract-plugin</artifactId>
                            <version>2.0.0</version>
                        </plugin>
                    </plugins>
                    <args>
                        <arg>-Ximmutable</arg>
                        <arg>-Xfluent-builder</arg>
                   </args>
                </configuration>
                <executions>
                    <execution>
                        <id>generate1</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>src/main/schema/1</schemaDirectory>
                            <bindingDirectory>src/main/binding/1</bindingDirectory>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc-1</generateDirectory>
                            <generatePackage>package1</generatePackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate2</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>src/main/schema/2</schemaDirectory>
                            <bindingDirectory>src/main/binding/2</bindingDirectory>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc-2</generateDirectory>
                            <generatePackage>package2</generatePackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

The problem now is that the generated classes in package `com.kscs.util.jaxb` (`Buildable`, `PropertyTree`, `Selector`, ...) are generated multiple times, which gives compilation errors:

    .../target/generated-sources/xjc-2/com/kscs/util/jaxb/PropertyTreeUse.java:[6,8] duplicate class: com.kscs.util.jaxb.PropertyTreeUse

What is the supported way for multiple executions? Alternatively, is it possible to generate several XSDs in one single execution, while still generating each XSD into their own package?

Thank you!

**Comment by mklemm** [comment]
you should be able to apply indivdual <args> for each execution. There you can add "-generateTools=no" as an argument to the -Ximmutable and -Xfluent-builder plugins:
```
<arg>-Ximmutable</>
<arg>-generateTools=no</args>
<arg>-Xfluent-builder</arg>
<arg>-generateTools=no</arg>
```

**Comment by mklemm** [comment]
btw you could set -generateTools=no globally (not per execution) and then add the jaxb2-rich-contract-plugin jar to your build class path
