### ISSUE TITLE
Wrong handling of unwrap for JAXBElement with wildcard type parameter

### ISSUE THREAD

**Issue by svavassori** [mklemm/jaxb2-rich-contract-plugin#37]
Hello,

I was moving my project from Java 8 to Java 10 and, after have upgraded the jaxb2-rich-contract plugin from 1.18.0 to 2.0.0 I discovered it generates some classes that are syntactically wrong, here an example:

```java
public CurveProperty.Builder<_B> withCurve(final JAXBElement<? extends AbstractCurveType> curve) {
    this.curve = curve;
    return this;
}

public CurveProperty.Builder<_B> withCurve(final? extends AbstractCurveType curve) {
    this.curve = new ObjectFactory().createCurvePropertyCurve(curve);
    return this;
}
```
the `final?` in the second method is clearly wrong and the compiler prints `net/opengis/gml/CurveProperty.java:[458,57] illegal start of type` error.

This happens because the parameter's type before unwap was `JAXBElement<? extends AbstractCurveType>`

In addition, the second error is that the `ObjectFactory` doesn't have any `createCurvePropertyCurve(AbstractCurveType curve)` method but only `createCurveProperty()`

After debugging the code, I think the problem is in how this code block handles wildcard types, maybe a proper check to keep only the bounded type will solve the problem: https://github.com/mklemm/jaxb2-rich-contract-plugin/blob/d8beaad88092d0091714735b28bf8ba87fb8c1d7/src/main/java/com/kscs/util/plugins/xjc/BuilderGenerator.java#L361-L376

This code block isn't present in the 1.18.0 version.
Unfortunately I didn't find the cause of the wrong `ObjectFactory` method selection.

If I disable the `-Xfluent-builder` builder generation in the pom.xml the classes are correctly created.

Do you have any idea on how it can be fixed or if there is a version if your plugin that doesn't generate this JAXBElement unwapper?

Thanks

**Comment by svavassori** [comment]
Hi,

I did some tests and I can confirm that commenting that part of the code (and the similar at line 493) will resolve the problem and allows compiling with Java 10.

Do you have an estimation date for the bigfix release? Isn't to put any pressure, just to know for how long I'll have to use the local patch.

**Comment by gtudan** [comment]
Hi Mirko,

I bumped into this as wenn and can confirm that reverting 687e849d72c66cdb54cc1f8b0c0c4bed4e5b9904 fixes the issue. If it helps  I can send a PR for the issue A small bugfix-release would be awesome!

- Gregor

**Comment by mklemm** [comment]
The offending commit 687e849 has been reverted in version 2.0.1, which has just been released.

**Comment by gtudan** [comment]
Awesome, thanks!
