### ISSUE TITLE
Compile Errors on collection _RO fields when using -Ximmutable and -Xfluent-builder together

### ISSUE THREAD

**Issue by tpunder** [mklemm/jaxb2-rich-contract-plugin#4]
When I try to compile code generated using both -Ximmutable and -Xfluent-builder I get compile errors from the Builder inner static class trying to access private _RO collection fields in the parent class:

    private transient List<AppType> app_RO = null;

Then in the Builder.init method there is code like:

    product.app_RO = ((app == null)?null:Collections.unmodifiableList(product.app));

Which causes:

    [error] ACES.java:240: error: app_RO has private access in ACES
    [error]     product.app_RO = ((app == null)?null:Collections.unmodifiableList(product.app));
    [error]            ^

I changed the _RO fields to be protected instead of private to avoid the error but I'm not sure if that's the best solution or not:  https://github.com/tpunder/jaxb2-rich-contract-plugin/commit/5020fe446eb279ec1fa9be3c0ad3f0dd45714521

**Comment by mklemm** [comment]
Hi tpunder,
Actually, I think the best solution would be to leave the "_RO" fields completely uninitialized by the builder, since they are lazily initialized anyway. I'm currently implementing this fix in version 1.5.2

**Comment by mklemm** [comment]
Thanks, your pull request has been integrated...
