### ISSUE TITLE
compiler errors with builder in combination with xs:date to java.util.Calendar conversion

### ISSUE THREAD

**Issue by techteam-bln** [mklemm/jaxb2-rich-contract-plugin#46]
If you define an xs:date field in an xml schema and define global bindings with:
<jaxb:globalBindings>
    <jaxb:javaType name="java.util.Calendar" xmlType="xsd:date"
        parseMethod="javax.xml.bind.DatatypeConverter.parseDate" printMethod="javax.xml.bind.DatatypeConverter.printDate" />
 </jaxb:globalBindings>

The generated builder code contains errors.

**Comment by mklemm** [comment]
It is designed to apply the builder patterns only to instances of classes defined within the current XML schema domain, so this is actually strange. I'll have a look into this...

**Comment by mklemm** [comment]
Fixed in 4.1.0

**Comment by davidsedlar** [comment]
Thanks a lot!

**Comment by mklemm** [comment]
Version 4.1.0 has just been released. It may take a while to appear on maven central, but it should be available soon.
