### ISSUE TITLE
Using -Xfluent-builder with Gradle Kotlin script fails

### ISSUE THREAD

**Issue by johkin** [mklemm/jaxb2-rich-contract-plugin#48]
There seems to be some version-issue with the constructor of JStaticJavaFile in line 403 of com.kscs.util.plugins.xjc.PluginContext.java when using the  "org.unbroken-dome.xjc" plugin in a Gradle Kotlin script build (build.gradle.kts).

For some reason it can't find the correct version of the constructor:

Caused by: java.lang.NoSuchMethodError: com.sun.codemodel.fmt.JStaticJavaFile.<init>(Lcom/sun/codemodel/JPackage;Ljava/lang/String;Ljava/lang/Class;Lcom/sun/codemodel/fmt/JStaticJavaFile$LineFilter;)V
        at com.kscs.util.plugins.xjc.PluginContext.writeSourceFile(PluginContext.java:403)
        at com.kscs.util.plugins.xjc.FluentBuilderPlugin.run(FluentBuilderPlugin.java:94)
        at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
        at com.sun.tools.xjc.model.Model$generateCode.call(Unknown Source)
        at org.unbrokendome.gradle.plugins.xjc.XjcGenerate.generateCode(XjcGenerate.groovy:196)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)

Attached test project to verify problem.
[fluent-builder.zip](https://github.com/mklemm/jaxb2-rich-contract-plugin/files/2957439/fluent-builder.zip)

**Comment by mklemm** [comment]
What is the JAXB runtime version that your Gradle XJC plugin is running under? And what is your Java runtime version?

**Comment by johkin** [comment]
Java runtime version is 1.8.0_181
After some investigation the XJC plugin i use ("org.unbroken-dome.xjc" version "1.4.2") seems to use Jaxb 2.2.11.
I've used the plugin without problems when I had a gradle-project that used the Groovy DSL, but the problem seems to be tied to using the Kotlin DSL in Gradle?
From what I understand the JStatisJavaFile is located in the tools.jar which will be removed in later versions of Java. I've seen packaged versions of com.sun.codemodel, but that would perhaps add other problems?

**Comment by mklemm** [comment]
Please try adding a dependency to JAXB-Api, JAXB-runtime and JAXB-xjc >=2.3.0 in the scope which is active while the XJC plugin is executed. jaxb2-rich-contract-plugin is designed to work with JAXB 2.3, it may fail to work with earlier JAXB versions.

**Comment by johkin** [comment]
I've tried by adding the following:

    xjcClasspath("javax.xml.bind:jaxb-api:2.3.1")
    xjcClasspath("org.glassfish.jaxb:jaxb-xjc:2.3.2")
    xjcClasspath("org.glassfish.jaxb:jaxb-runtime:2.3.2")

Still yields the same error. The jaxb-xjc adds transitive dependencies to jaxb-codemodel, which probably adds the correct version to the classpath, but when I use gradle-kotlin-dsl it seems to pickup another version from some other dependecy. This problem should perhaps be addressed to the Gradle community?

**Comment by johkin** [comment]
I still haven't found a good explanation for why I have the problem. I tried to convert the Gradle build files back to the Groovy DSL, but that didn't make any change. Seems to be more of a common Gradle issue?

However, when going back to version 1.18.0 of the plugin, it works fine and I can generate code with the fluent-builder plugin. Which is probably good enough for now!
