### ISSUE TITLE
Publish to Maven Central!

### ISSUE THREAD

**Issue by tpunder** [mklemm/jaxb2-rich-contract-plugin#5]
It would be great to have this published to maven central so people don't have to depend on a non-standard repository that could become unavailable or go away at any time.

**Comment by mklemm** [comment]
In progress

**Comment by cachescrubber** [comment]
Maven Central would be great!

In the meantime, please update your documentation. I had to use the following configuration in order to use your private repo:

 ```xml
<repositories>
    <repository>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
        <checksumPolicy>warn</checksumPolicy>
      </releases>
      <id>jaxb2-plugins</id>
      <name>JAXB2 XJC Plugin Repository</name>
      <url>http://maven.klemm-scs.com/release</url>
      <layout>default</layout>
    </repository>
  </repositories>
```
- repository instead of pluginRepository.
- releases enabled

**Comment by mklemm** [comment]
Version 1.5.2 has been released on Maven central. Many generated names in source code can now be customized via command-line options. Please note: The groupId had to change to com.klemm-scs.util because of Sonatype Central hosting requirements.
