### ISSUE TITLE
problems generating setter

### ISSUE THREAD

**Issue by gurpiarbassi** [mklemm/jaxb2-rich-contract-plugin#56]
I'm having issue generating the correct method for my repeating elements in xml.

```
<bookingCodeRecord>
        <recordType>B</recordType>
        <sequenceNumber>0887291224</sequenceNumber>
        <lineNumber>30</lineNumber>
        <bookingCodeString>abc</bookingCodeString>
        <carrierName>mailer</carrierName>
    </bookingCodeRecord>
```

I have several of these in my xml file which I cannot deserialise. Note: there is no wrapper element encapsulating these records.

I get the following error when deserialising:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `atg.test. BookingCodeRecord ` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('D')
 at [Source: (StringReader); line: 99, column: 22] (through reference chain: atg.test.Order["bookingCodeRecord"]->java.util.ArrayList[0])


```

Either i'm generating the objects wrong or it's an issue with Jackson which I'm using to deserialise.

**Comment by mklemm** [comment]
Actual serialization and deserialization, and things involving Jackson, seem to be out of the scope of this JAXB plugin. Could you please further explain how your issue relates to jaxb2-rich-contract-plugin?

**Comment by gurpiarbassi** [comment]
Can you close this issue please @mklemm ?
It's been a long time that I can't recall the problem anymore.
