### ISSUE TITLE
Wrong constructor arguments call for builder plugin

### ISSUE THREAD

**Issue by jevanlingen** [mklemm/jaxb2-rich-contract-plugin#57]
I am trying to replace the `fluent-api` plugin with the `fluent-builder` plugin. But after adding the `jaxb2-rich-contract-plugin` dependency and running a `mvn clean install`, I ran into an errror, here the simplified error log:

```
package.Builder(package.Builder<_B>, package.ResidenceType, boolean)
is not applicable for constructor
package.Builder(package.Builder<_B>, package.ResidenceType, boolean, com.kscs.util.jaxb.PropertyTree, com.kscs.util.jaxb.PropertyTreeUse)
(actual and formal argument lists differ in length)
```

Note: I use Java 8, jaxb2-rich-contract-plugin 2.0.1 and JAXB 2.3 in combination with the `cxf-codegen-plugin`.

**Comment by mklemm** [comment]
Did you try activating the copy plugin as well? Maybe this helps...

**Comment by mklemm** [comment]
No more user responses, closed.
