### ISSUE TITLE
No hashcode, equals or toString

### ISSUE THREAD

**Issue by timrobertson100** [mklemm/jaxb2-rich-contract-plugin#6]
This is a great tool, but I am a little surprised there are no hashcode, equals or toString.
What is the motivation for that please?

A really nice addition might be auto generation of Guava based methods optionally controlled by an argument.

**Comment by mklemm** [comment]
Update: You may wish to try out the new [jaxb-format-plugin](http://github.com/mklemm/jaxb-format-plugin) for a flexible way to generate toString() methods (also works for hashCode(), but there is no example yet).

**Comment by mklemm** [comment]
From my point of view it is not planned to add equals(), hashCode() or toString() in the near future. So I'm closing this now...
