### ISSUE TITLE
Fluent Builder breaks when generating lists since 1.6.4 release

### ISSUE THREAD

**Issue by roelofjansen** [mklemm/jaxb2-rich-contract-plugin#61]
Hi,

I'm in the process of migrating to Java 11+. I am now facing a problem I cannot solve. It already occurred when I tried updating from 1.6.3 to 1.6.4 (with JDK 8).

I now use your plugin v2.0.1 and JDK11..

I use the following plugin to generate the code:

```xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>jaxws-maven-plugin</artifactId>
    <version>2.6</version>
</plugin>
```
With arguments:
      <args>
        <arg>-B-Xfluent-builder</arg>
      </args>

This is the command line:

jaxws:wsimport: [-keep, -s, '/home/eopg/projects/eopg/koppelvlakken/eopg-aanvraagservice-koppelvlak/target/generated-sources/wsimport', -d, '/home/eopg/projects/eopg/koppelvlakken/eopg-aanvraagservice-koppelvlak/target/classes', -verbose, -encoding, UTF-8, -extension, -Xnocompile, -B-Xfluent-builder, -Xdebug, -b, 'file:myservice.wsdl']

Problem:
Whenever I use maxOccurs="unbound" within an element a List field is generated in the generated Java class;

e.g.
```xml
  <xsd:complexType name="stamtabelItem">
    <xsd:sequence>
      <xsd:element name="omschrijving" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
```

Resulting in the following Java code snippet: 
```java
public class StamtabelItem implements Serializable, Cloneable
{
    @XmlElement(required = true)
    @NotNull
    @Size(min = 1)
    @Valid
    protected java.util.List<StamtabelItem.Omschrijving> omschrijving;
...
}
```

Up to 1.6.3:
```java
public Builder(final PB _parentBuilder, final StamtabelItem _other, final boolean _copy) {
    this._parentBuilder = _parentBuilder;
    if (_copy) {
        this._other = null;
        if (_other.omschrijving == null) {
            this.omschrijving = null;
        } else {
            this.omschrijving = new ArrayList<StamtabelItem.Omschrijving.Builder<StamtabelItem.Builder<PB>>>();
            for (StamtabelItem.Omschrijving _item: _other.omschrijving) {
                this.omschrijving.add(((_other.omschrijving == null)?null:_item.<StamtabelItem.Builder<PB> >newCopyBuilder()));
            }
        }
    } else {
        this._other = _other;
    }
}
```

After 1.6.3:
```java
public Builder(final _B _parentBuilder, final StamtabelItem _other, final boolean _copy) {
    this._parentBuilder = _parentBuilder;
    if (_other!= null) {
        if (_copy) {
            _storedValue = null;
            this.omschrijving = _other.omschrijving;
        } else {
            _storedValue = _other;
        }
    } else {
        _storedValue = null;
    }
}
```

Resulting in: 
![afbeelding](https://user-images.githubusercontent.com/20125094/95196000-adca2000-07d7-11eb-9f1e-069e2cde73fd.png)

Java ERROR:
incompatible types: java.util.List<StamtabelItem.Omschrijving> cannot be converted to java.util.List<StamtabelItem.Omschrijving.Builder<StamtabelItem.Builder<_B>>>

I tried pinpointing what has changed between 1.6.3 and 1.6.4 but I trust you can do better :+1: 

Kind regards,
Roelof.

**Comment by mklemm** [comment]
This seems to be a specific issue with your project. Is it possible for you to package all the relevant files into a maven project and attach it here as zip?

**Comment by roelofjansen** [comment]
That will take some time but I can do that

**Comment by roelofjansen** [comment]
I didn't create a package yet but started a new project with the same sources. It seems that the problem lies when you override the default package name of the classes being generated. If I leave that option out it works!

**Comment by roelofjansen** [comment]
I found the problem. In my jaxbbinding xml config I had overidden the package name to the same package as it would be generated without the mapping. Once I removed that mapping it worked miraculously! So this issue can be closed now!
