### ISSUE TITLE
Fix javadoc for copyTo methods

### ISSUE THREAD

**Issue by oolubayo** [mklemm/jaxb2-rich-contract-plugin#68]
copyTo methods are generated with an invalid javadoc due to a bad reference to copyOf method. Executing `mvn javadoc:javadoc` on classes with this javadoc will fail due to the copyOf reference. This error occurs because the copyOf method does not exist in the client class, but only exists in the generated builder class.

Possible Solution:
Remove the `{@link copyOf}` referenced in the generated javadoc and replace with `copyOf` (without the @link code).

**Comment by mklemm** [comment]
Fixed in 4.1.0

**Comment by mklemm** [comment]
Version 4.1.0 has just been released. It may take a while to appear on maven central, but it should be available soon.
