### ISSUE TITLE
Change documentation according latest version of maven-jaxb2-plugin

### ISSUE THREAD

**Issue by laurentschoelens** [mklemm/jaxb2-rich-contract-plugin#74]
The `maven-jaxb2-plugin` has been active recently with support of jaxb3/jaxb4 (see [repository](https://github.com/highsource/jaxb-tools)) and was renamed to `jaxb-tools` since the related jaxb-repository of highsource were merged into the original repository of maven-jaxb2-plugin

In order to help people getting the latest working version of jaxb maven plugin, the README should point out the new coordinates of the plugin which support jaxb2.3

From
`org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.14.0`
To
`org.jvnet.jaxb:jaxb-maven-plugin:2.0.9`

**Comment by mklemm** [comment]
Fixed in 4.0.0
