### ISSUE TITLE
Fluent Builder writes dependent classes into the root of the project instead of a target directory for the generated classes

### ISSUE THREAD

**Issue by dadrus** [mklemm/jaxb2-rich-contract-plugin#9]
First of all thank you for the great plugin.

While using it (actually only the fluent builder) I've encountered the issue, that the required classes (like PropertyTree, etc) are copied into the root directory of the project instead of the configured sourceDestDir directory. E.g. let's say my project resides in the directory foo und the directory to put generated classes is configured like <sourceDestDir>${basedir}/target/generated-sources/java</sourceDestDir>. So instead of putting the dependencies into foo/target/generated-sources/java all of them are placed into foo (foo/com/kscs/util/jaxb/PropertyTree.java etc are created). This is due the fact, that copiing of dependencies is done the following way: PluginUtil.writeSourceFile(getClass(), opt.targetDir, PropertyTreeUse.class.getName());
The propblem seems to be opt.targetDir. It is defined as new File(".") in the Options class and is not modified at any time. For the sake of completeness here my plugin configuration:
```xml
<plugin>
    <groupId>org.jvnet.jax-ws-commons</groupId>
    <artifactId>jaxws-maven-plugin</artifactId>
    <version>2.3</version>
    <dependencies>
        <dependency>
            <groupId>org.jvnet.jaxb2_commons</groupId>
            <artifactId>jaxb2-namespace-prefix</artifactId>
            <version>1.1</version>
        </dependency>
        <dependency>
            <groupId>com.kscs.util</groupId>
            <artifactId>jaxb2-rich-contract-plugin</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.jvnet.jaxb2_commons</groupId>
            <artifactId>jaxb2-commons-lang</artifactId>
            <version>2.4</version>
        </dependency>
    </dependencies>
    <configuration>
        <xjcArgs>
            <xjcArg>-Xnamespace-prefix</xjcArg>
            <xjcArg>-Xfluent-builder</xjcArg>
            <xjcArg>-Xcommons-lang</xjcArg>
            <xjcArg>-verbose</xjcArg>
        </xjcArgs>
    </configuration>
    <executions>
        <execution>
            <id>foo</id>
            <configuration>
                <wsdlDirectory>${project.build.outputDirectory}/META-INF/wsdl</wsdlDirectory>
                <wsdlFiles>
                    <wsdlFile>foo.wsdl</wsdlFile>
                </wsdlFiles>
                <wsdlLocation>http://foo.com/foo?wsdl</wsdlLocation>
                <keep>true</keep>
                <sourceDestDir>${basedir}/target/generated-sources/java</sourceDestDir>
                <staleFile>${project.build.directory}/jaxws/stale/wsdl.foo.done</staleFile>
                <extension>true</extension>
                <bindingDirectory>${basedir}/src/main/xjb</bindingDirectory>
            </configuration>
            <goals>
                <goal>wsimport</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Maybe I just miss some configuration option.

Thank you for your support.

Regards,
Dimtirij

**Comment by msglaser** [comment]
Hello Mirko,
I'm using Release 1.3.6. The bug mentioned above is not corrected yet, right?
I cannot get your workaround running. I don't get the option „-generate-tools=n“ passed to your plugin. Do you have an example on how to do that within a pom? I use your plugin together with the plugin "jaxws-maven-plugin" to run to goal "wsimport". Using <arg>-B-Ximmutable</arg> works fine. But <arg>-B-generate-tools=n</arg> does result in "no such JAXB option: -generate-tools=n".
Tks and regards
Markus

**Comment by mklemm** [comment]
Hi Markus,
could you please send an excerpt from your pom.xml? Honestly, I couldn't reproduce, how the files are generated into the root of the project tree... If you are also calling the plugin via jaxws-import, this may be the reason, because up until now it has only been tested with the maven-jaxb2-plugin.
As to the -generate-tools='n' option: A pull request contributed a change that made all option names unique across different plugins. This involved renaming the -generate-tools option to "-fluent-builder-generate-tools". Unfortunately, this change wasn't reflected in the documentation. It is a temporary fix anyway, because in the next version plguin options will be parsed as is intended by the JAXB reference implementation in order after the "-Xplugin"-option.
So, currently, to use the workaround, you will have to add <xjcArg>-fluent-builder-generate-tools=n</xjcArg> to your configuration section...

**Comment by msglaser** [comment]
Hello Mirko
Thanks a lot for your fast reply. The option -fluent-builder-generate-tools=n works a lot better :-) Would be cool to update your documentation soon.

The pom I use is as follows (I just replaced the internal stuff with ...). Without the mentioned option, the files BuilderUtilities.java, PropertyTree.java, PropertyTreeUse.java and Selector.java are place unter "<project>/com/ksc/util/jaxb". I use maven 3.0.4. Hopefully you get the problem reproduced with that information.

Kind regards
Markus

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>...</groupId>
		<artifactId>...</artifactId>
		<version>...-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>

	<artifactId>....</artifactId>
	<name>...</name>
	<packaging>jar</packaging>

	<dependencies>
		
		<dependency>
			<groupId>org.jvnet.jaxb2_commons</groupId>
			<artifactId>jaxb2-basics-runtime</artifactId>
			<version>0.9.1</version>
		</dependency>

		<dependency>
			<groupId>com.kscs.util</groupId>
			<artifactId>jaxb2-rich-contract-plugin</artifactId>
			<version>1.3.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jvnet.jax-ws-commons</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<dependencies>
					
					<dependency>
						<groupId>org.jvnet.jaxb2_commons</groupId>
						<artifactId>jaxb2-basics</artifactId>
						<version>0.6.4</version>
					</dependency>
					<dependency>
						<groupId>com.kscs.util</groupId>
						<artifactId>jaxb2-rich-contract-plugin</artifactId>
						<version>1.3.0</version>
					</dependency>
				</dependencies>
				<configuration>
					<wsdlDirectory>src/main/resources/wsdl</wsdlDirectory>
				</configuration>
				<executions>
					<execution>
						<id>WSDL</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
							<verbose>true</verbose>
							<packageName>yxz.soap
							</packageName>
							<wsdlFiles>
								<wsdlFile>xyz.wsdl</wsdlFile>
							</wsdlFiles>
							<args>
								<arg>-B-XtoString</arg>
								<arg>-B-Xequals</arg>
								<arg>-B-Ximmutable</arg>
								<arg>-B-Xfluent-builder</arg>
								<arg>-B-fluent-builder-generate-tools=n</arg>
							</args>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by mklemm** [comment]
Just now, version 1.4.0 of the plugin has been released, where this bug should have been fixed.
The command-line options are now again named as documented, but for each plugin, the options have to be given immediately after the plugin activation option ("-X..."), this way, there are no naming conflicts anymore between options of different plugins.
Please let me know if this fixes it for you.
Cheers,
Mirko

**Comment by dadrus** [comment]
Hello Mirco,

Cool. It works now. Everything is at the expected place. Thank you.

Regards,
Dimitrij
